#!/bin/bash

source config

if [ $SQLEngine == Shell ]; then
	source tools/useshell
	./collectResult
elif [ $SQLEngine == C ]; then
	source tools/useC
	./collectResult
else
	echo "Not supported SQL engine:"$SQLEngine
fi
